# install dependencies for cf4minikube
tap "k14s/tap"
tap "cloudfoundry/tap"

brew "asciinema"
brew "cloudfoundry/tap/cf-cli@7"
brew "cloudfoundry/tap/bosh-cli"
brew "imgpkg"
brew "jq"
brew "kapp"
brew "kbld"
brew "kubectl"
brew "minikube"
brew "kwt"
brew "vendir"
brew "yq"
brew "ytt"
